[package]
name = "project-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
clap = { version = "4.1", features = ["derive"]} ##for CLI argument parsing
chrono = { version = "0.4", features = ["serde"]}
